### ISSUE TITLE
Client Console Not Tracking

### ISSUE THREAD

**Issue by yiruzu** [alp1x/um-error-tracker#1]
It only tracks the errors in the server console but not in the client console.

**Comment by alp1x** [comment]
![image](https://github.com/alp1x/um-error-tracker/assets/56808589/a931d195-8519-44b9-abb6-3704f3b71280)

**Comment by yiruzu** [comment]
Oh, okay, I missed that part. But this resource seems unnecessary, to be honest, because the errors in the client console are much more likely to be missed. Still, a cool script.
